# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quotes for developers
email: fl@fortrabbit.com
description: > # this means to ignore newlines until "baseurl:"
  A few hundred motivating quotes, 
  related to programming culture, 
  developing software and PHP
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fortrabbit.github.io/quotes" # the base hostname & protocol for your site
twitter_username: frank_laemmer
github_username:  frank-laemmer
css_assetpath:  //s3-eu-west-1.amazonaws.com/fortrabbit-static

# Build settings
markdown: kramdown
